// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: transform/transform.proto

package transform

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransformClient is the client API for Transform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransformClient interface {
	// Transforms image
	Transform(ctx context.Context, opts ...grpc.CallOption) (Transform_TransformClient, error)
}

type transformClient struct {
	cc grpc.ClientConnInterface
}

func NewTransformClient(cc grpc.ClientConnInterface) TransformClient {
	return &transformClient{cc}
}

func (c *transformClient) Transform(ctx context.Context, opts ...grpc.CallOption) (Transform_TransformClient, error) {
	stream, err := c.cc.NewStream(ctx, &Transform_ServiceDesc.Streams[0], "/transform.Transform/Transform", opts...)
	if err != nil {
		return nil, err
	}
	x := &transformTransformClient{stream}
	return x, nil
}

type Transform_TransformClient interface {
	Send(*Pixel) error
	Recv() (*Pixel, error)
	grpc.ClientStream
}

type transformTransformClient struct {
	grpc.ClientStream
}

func (x *transformTransformClient) Send(m *Pixel) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transformTransformClient) Recv() (*Pixel, error) {
	m := new(Pixel)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransformServer is the server API for Transform service.
// All implementations must embed UnimplementedTransformServer
// for forward compatibility
type TransformServer interface {
	// Transforms image
	Transform(Transform_TransformServer) error
	mustEmbedUnimplementedTransformServer()
}

// UnimplementedTransformServer must be embedded to have forward compatible implementations.
type UnimplementedTransformServer struct {
}

func (UnimplementedTransformServer) Transform(Transform_TransformServer) error {
	return status.Errorf(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedTransformServer) mustEmbedUnimplementedTransformServer() {}

// UnsafeTransformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransformServer will
// result in compilation errors.
type UnsafeTransformServer interface {
	mustEmbedUnimplementedTransformServer()
}

func RegisterTransformServer(s grpc.ServiceRegistrar, srv TransformServer) {
	s.RegisterService(&Transform_ServiceDesc, srv)
}

func _Transform_Transform_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransformServer).Transform(&transformTransformServer{stream})
}

type Transform_TransformServer interface {
	Send(*Pixel) error
	Recv() (*Pixel, error)
	grpc.ServerStream
}

type transformTransformServer struct {
	grpc.ServerStream
}

func (x *transformTransformServer) Send(m *Pixel) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transformTransformServer) Recv() (*Pixel, error) {
	m := new(Pixel)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Transform_ServiceDesc is the grpc.ServiceDesc for Transform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transform.Transform",
	HandlerType: (*TransformServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transform",
			Handler:       _Transform_Transform_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transform/transform.proto",
}
